### ISSUE TITLE
Please update, to support the latest features of LVGL

### ISSUE THREAD

**Issue by sn00zerman** [OPHoperHPO/lilygo-ttgo-twatch-2020-micropython#3]
I'm missing the dynamic font loading, so please update to micropython 1.13.

**Comment by sn00zerman** [comment]
closed !

**Comment by miathedev** [comment]
How did you load another fonts?
I got stuck at this.

**Comment by OPHoperHPO** [comment]
Currently in progress

**Comment by OPHoperHPO** [comment]
I have updated micropython and lvgl to the latest versions. You can see it in the [1.13](https://github.com/OPHoperHPO/lilygo-ttgo-twatch-2020-micropython/tree/1.13) branch.
