### ISSUE TITLE
how to upload the prebuild firmware in the ttgo watch ?

### ISSUE THREAD

**Issue by picpic020960** [OPHoperHPO/lilygo-ttgo-twatch-2020-micropython#4]
probably some particularity whit adress , bootloader ...?
example script possible with esptool.py 
( test with python esptool.py --chip esp32 --port /dev/ttyUSB0 write_flash -z 0x1000 firmware.bin   ==> nothing with the watch )
thank's a lot

edit : OK
but interpreter works only with Thonny (IDE) ?
with serial arduino IDE ... no prompt    :-(
one trick ?
thank's

**Comment by miathedev** [comment]
## IDE
I would like to recommend you:

rshell
`https://github.com/dhylands/rshell`

in connection with pycharm
`https://www.jetbrains.com/de-de/pycharm/`

## Flashing
you should always first erase the flash with:
`esptool.py --port /dev/ttyUSB0 erase_flash`

then flash it:
`esptool.py --port /dev/ttyUSB0 write_flash 0x1000 firmware.bin`

I married pycharm and rshell with configuring it as "terminal" replacement. (Settings -> Terminal)

**Comment by picpic020960** [comment]
OK
