### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by ndrogness** [OPHoperHPO/lilygo-ttgo-twatch-2020-micropython#7]
Gets all the way through the build process and bails out on the linker on application.elf:

LINK build-LILYGO_T_WATCH_2020_V1/application.elf	
/home/ndrogness/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-ld: build-LILYGO_T_WATCH_2020_V1/lvgl_esp32_drivers/lvgl_tft/st7789.o:(.literal.st7789_send_data+0x0): undefined reference to `disp_spi_send_data'
/home/ndrogness/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-ld: build-LILYGO_T_WATCH_2020_V1/lvgl_esp32_drivers/lvgl_tft/st7789.o:(.literal.st7789_flush+0x0): undefined reference to `disp_spi_send_colors'
/home/ndrogness/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-ld: build-LILYGO_T_WATCH_2020_V1/lvgl_esp32_drivers/lvgl_tft/st7789.o: in function `st7789_send_data':
/home/ndrogness/lilygo-ttgo-twatch-2020-micropython/ports/esp32/boards/LILYGO_T_WATCH_2020_V1/c_drivers/lvgl_esp32_drivers/lvgl_tft/st7789.c:191: undefined reference to `disp_spi_send_data'
/home/ndrogness/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-ld: build-LILYGO_T_WATCH_2020_V1/lvgl_esp32_drivers/lvgl_tft/st7789.o: in function `st7789_send_cmd':
/home/ndrogness/lilygo-ttgo-twatch-2020-micropython/ports/esp32/boards/LILYGO_T_WATCH_2020_V1/c_drivers/lvgl_esp32_drivers/lvgl_tft/st7789.c:184: undefined reference to `disp_spi_send_data'
/home/ndrogness/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-ld: build-LILYGO_T_WATCH_2020_V1/lvgl_esp32_drivers/lvgl_tft/st7789.o: in function `st7789_send_color':
/home/ndrogness/lilygo-ttgo-twatch-2020-micropython/ports/esp32/boards/LILYGO_T_WATCH_2020_V1/c_drivers/lvgl_esp32_drivers/lvgl_tft/st7789.c:197: undefined reference to `disp_spi_send_colors'
Makefile:802: recipe for target 'build-LILYGO_T_WATCH_2020_V1/application.elf' failed
make: *** [build-LILYGO_T_WATCH_2020_V1/application.elf] Error 1

# makefile:
ESPIDF ?= $(HOME)/esp/esp-idf-v4/esp-idf
CROSS_COMPILE ?= $(HOME)/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-
PYTHON=python3

BOARD ?= LILYGO_T_WATCH_2020_V1
PORT ?= /dev/ttyUSB0
FLASH_MODE ?= dio
FLASH_SIZE ?= 16MB
USER_C_MODULES=boards/LILYGO_T_WATCH_2020_V1/c_drivers

include Makefile

**Comment by OPHoperHPO** [comment]
I know about this bug. It has been already fixed in the 1.13 branch. You can use updated micropython version from this branch with fixes or fix this problem by yourself with copy c_drivers folder from 1.13 branch to c_drivers folder from master branch.

**Comment by ndrogness** [comment]
I was able to compile after checking out your 1.13 branch:

git clone --single-branch --branch 1.3
git submodule update --init --recursive

I left you something via paypal for the quick response.  Thanks!
