### ISSUE TITLE
compiling error - undefined reference to disp_spi_send_data

### ISSUE THREAD

**Issue by thebotmakes** [OPHoperHPO/lilygo-ttgo-twatch-2020-micropython#8]
Hi, I'm having an issue when I try to build a new build - firmware version works fine, and all I've changed is the config file to add in two new fonts. Gets pretty far through the compile and then I get these errors:

_LINK build-LILYGO_T_WATCH_2020_V1/application.elf
xtensa-esp32-elf-ld: build-LILYGO_T_WATCH_2020_V1/lvgl_esp32_drivers/lvgl_tft/st7789.o:(.literal.st7789_send_data+0x0): undefined reference to `disp_spi_send_data'
xtensa-esp32-elf-ld: build-LILYGO_T_WATCH_2020_V1/lvgl_esp32_drivers/lvgl_tft/st7789.o:(.literal.st7789_flush+0x0): undefined reference to `disp_spi_send_colors'
xtensa-esp32-elf-ld: build-LILYGO_T_WATCH_2020_V1/lvgl_esp32_drivers/lvgl_tft/st7789.o: in function `st7789_send_data':
/home/pi/lilygo-ttgo-twatch-2020-micropython/ports/esp32/boards/LILYGO_T_WATCH_2020_V1/c_drivers/lvgl_esp32_drivers/lvgl_tft/st7789.c:192: undefined reference to `disp_spi_send_data'
xtensa-esp32-elf-ld: build-LILYGO_T_WATCH_2020_V1/lvgl_esp32_drivers/lvgl_tft/st7789.o: in function `st7789_send_cmd':
/home/pi/lilygo-ttgo-twatch-2020-micropython/ports/esp32/boards/LILYGO_T_WATCH_2020_V1/c_drivers/lvgl_esp32_drivers/lvgl_tft/st7789.c:185: undefined reference to `disp_spi_send_data'
xtensa-esp32-elf-ld: build-LILYGO_T_WATCH_2020_V1/lvgl_esp32_drivers/lvgl_tft/st7789.o: in function `st7789_send_color':
/home/pi/lilygo-ttgo-twatch-2020-micropython/ports/esp32/boards/LILYGO_T_WATCH_2020_V1/c_drivers/lvgl_esp32_drivers/lvgl_tft/st7789.c:198: undefined reference to `disp_spi_send_colors'
make: *** [Makefile:803: build-LILYGO_T_WATCH_2020_V1/application.elf] Error 1_

Any ideas?  Thanks, Scott.

**Comment by thebotmakes** [comment]
should have said - not new fonts, just adding in some bigger versions of the standard montserrat font.

**Comment by OPHoperHPO** [comment]
Hi, @thebotmakes, 
Are you trying to compile master branch? Try to compile version in the 1.13 branch.

**Comment by thebotmakes** [comment]
Hi, yeah pretty sure I am but let me check in the morning, thanks.

**Comment by OPHoperHPO** [comment]
@thebotmakes,

Version 1.13 should compile. I just checked it out on Github Actions. If you have problems with this on your computer, try fork the repository, enable Github Actions, and make the necessary changes in branch 1.13. Then, in your Github Actions, the image build will automatically start. After build, in the build artifacts you can see the firmware.bin file

**Comment by thebotmakes** [comment]
Thanks a lot - shifting to 1.13 did the trick (and I learned something cool on GitHub too !).  Really appreciate the help!
